#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinFly Configuration File:
# Use the § symbol for color coding.
#   Default Config:
#      onJoin_FlyReset: true
#      onDamage_FlyReset: true
#      fly_enabled: "Flight mode activated"
#      fly_disabled: "Flight mode deactivated"

# The below config allows the plugin to reset flight mode when joining the server
onJoin_FlyReset: true

# The below config allows the plugin to reset flight mode when pvping in the server
onDamage_FlyReset: true

# The below config allows you to send a message to the player when they enable fly
fly_enabled: "§aFlight mode activated"

# The below config allows you to send a message to the player when they disable fly
fly_disabled: "§cFlight mode deactivated"
...